Update build_apk.yml

diff --git a/.github/workflows/build_apk.yml b/.github/workflows/build_apk.yml
--- a/.github/workflows/build_apk.yml
+++ b/.github/workflows/build_apk.yml
@@ -33,12 +33,12 @@ jobs:
             libffi-dev \
             git \
             unzip \
-            openjdk-11-jdk  # Добавлено для Java
+            openjdk-11-jdk
 
     - name: Install Cython
       run: pip3 install cython
 
-    - name: Install Android SDK
+    - name: Install Android SDK and Build-Tools
       run: |
         mkdir -p ~/android-sdk
         cd ~/android-sdk
@@ -47,10 +47,14 @@ jobs:
         yes | ./cmdline-tools/bin/sdkmanager --sdk_root=~/android-sdk --licenses
         ./cmdline-tools/bin/sdkmanager --sdk_root=~/android-sdk "platform-tools" "build-tools;34.0.0" "platforms;android-34"
 
+        # Проверка наличия aidl
+        ls ~/android-sdk/build-tools/34.0.0/aidl || echo "Aidl not found!"
+
     - name: Set environment variables
       run: |
         echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
         echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
+        echo "$HOME/android-sdk/build-tools/34.0.0" >> $GITHUB_PATH  # Добавлен путь к build-tools
 
     - name: Install Buildozer and Kivy
       run: pip install buildozer kivy
