Update build_apk.yml

diff --git a/.github/workflows/build_apk.yml b/.github/workflows/build_apk.yml
--- a/.github/workflows/build_apk.yml
+++ b/.github/workflows/build_apk.yml
@@ -45,16 +45,16 @@ jobs:
         wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
         unzip commandlinetools-linux-9477386_latest.zip
         yes | ./cmdline-tools/bin/sdkmanager --sdk_root=~/android-sdk --licenses
-        ./cmdline-tools/bin/sdkmanager --sdk_root=~/android-sdk "platform-tools" "build-tools;34.0.0" "platforms;android-34"
+        ./cmdline-tools/bin/sdkmanager --sdk_root=~/android-sdk "platform-tools" "build-tools;36.0.0" "platforms;android-36"
 
         # Проверка наличия aidl
-        ls ~/android-sdk/build-tools/34.0.0/aidl || echo "Aidl not found!"
+        ls ~/android-sdk/build-tools/36.0.0/aidl || echo "Aidl not found!"
 
     - name: Set environment variables
       run: |
         echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
         echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
-        echo "$HOME/android-sdk/build-tools/34.0.0" >> $GITHUB_PATH  # Добавлен путь к build-tools
+        echo "$HOME/android-sdk/build-tools/36.0.0" >> $GITHUB_PATH  # Добавлен путь к build-tools
 
     - name: Install Buildozer and Kivy
       run: pip install buildozer kivy
